# Generated by Django 5.0.1 on 2024-01-26 14:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название продукта",
                        max_length=200,
                        verbose_name="Название продукта",
                    ),
                ),
                (
                    "measurement_units",
                    models.CharField(
                        help_text="Единицы измерения",
                        max_length=200,
                        verbose_name="Единицы измерения",
                    ),
                ),
                (
                    "cooking_amount",
                    models.PositiveSmallIntegerField(
                        help_text="Количество приготовлений",
                        verbose_name="Количество приготовлений",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название",
                        max_length=200,
                        unique=True,
                        verbose_name="Название рецепта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
                "ordering": ("-name",),
            },
        ),
        migrations.CreateModel(
            name="RecipeProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(5000),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="Вес",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукты рецепта",
                "verbose_name_plural": "Продукты рецептов",
            },
        ),
        migrations.AddConstraint(
            model_name="products",
            constraint=models.UniqueConstraint(
                fields=("name", "measurement_units"), name="name_measurement_units"
            ),
        ),
        migrations.AddField(
            model_name="recipeproducts",
            name="products",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipeproducts",
                to="recipe.products",
                verbose_name="Продукты",
            ),
        ),
        migrations.AddField(
            model_name="recipeproducts",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipeproducts",
                to="recipe.recipe",
                verbose_name="Рецепт",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="products",
            field=models.ManyToManyField(
                related_name="recipe_products",
                through="recipe.RecipeProducts",
                to="recipe.products",
                verbose_name="Продукты",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeproducts",
            constraint=models.UniqueConstraint(
                fields=("recipe", "products"), name="recipe_products"
            ),
        ),
    ]
