# Generated by Django 5.0.1 on 2024-01-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0002_alter_products_cooking_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeproducts",
            name="measurement_units",
            field=models.CharField(
                default="г",
                help_text="Единицы измерения",
                max_length=200,
                verbose_name="Единицы измерения",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="measurement_units",
            field=models.CharField(
                default="г",
                help_text="Единицы измерения",
                max_length=200,
                verbose_name="Единицы измерения",
            ),
        ),
    ]
